envName: staging

default:
  app:
    destination:
      namespace: staging
      server: https://kubernetes.default.svc
    source:
      targetRevision: staging

applications:
  pdf-service:
    enabled: false
    enableAutoSync: false

  mailqueue:
    enabled: false
    enableAutoSync: false

  api-gateway:
    enabled: false
    enableAutoSync: false

  auth-service:
    enabled: false
    enableAutoSync: false
